### ISSUE TITLE
Trying use the API with NodeJS example

### ISSUE THREAD

**Issue by mrbianchi** [greenaddress/GreenAddressAPI#1]
I get this when I run it on console 
```
PS C:\Users\M\Desktop\greenaddress> node index
Error {
  error: 'com.greenaddress.error',
  args:
   [ 'http://greenaddressit.com/error#internal',
     'Client or browser cache too old. Please upgrade your app, or refresh the page!',
     {} ],
  kwargs: {} }
```
When the sentence ` return session.call('com.greenaddress.login.authenticate',[[signature.r.toString(), signature.s.toString()], false]); ` is executed, the promise retrieve reject

**Comment by trongham** [comment]
> I get this when I run it on console
> 
> ```
> PS C:\Users\M\Desktop\greenaddress> node index
> Error {
>   error: 'com.greenaddress.error',
>   args:
>    [ 'http://greenaddressit.com/error#internal',
>      'Client or browser cache too old. Please upgrade your app, or refresh the page!',
>      {} ],
>   kwargs: {} }
> ```
> 
> When the sentence `return session.call('com.greenaddress.login.authenticate',[[signature.r.toString(), signature.s.toString()], false]);` is executed, the promise retrieve reject
